[versions]
datetime = "0.7.1-0.6.x-compat"
lanterna = "3.1.3"
serialization = "1.9.0"
kaml = "0.97.0"
okhttp = "5.1.0"
coroutines = "1.10.2"
kotlin = "2.2.20"

[libraries]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime" , version.ref = "datetime" }
lanterna = { group = "com.googlecode.lanterna", name = "lanterna", version.ref = "lanterna" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
